{{- if .Values.fineract_connector.enabled -}}

apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-fineract"
  labels:
    app: ph-ee-connector-ams-fineract
spec:
  replicas: {{ .Values.fineract_connector.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-ams-fineract
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-fineract
      annotations:
{{- if .Values.fineract_connector.deployment.annotations }}
{{ toYaml .Values.fineract_connector.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-ams-fineract
          image: "{{ .Values.fineract_connector.image }}:{{ .Values.fineract_connector.imageTag }}"
          ports:
            - containerPort: 5000
              protocol: TCP
            - containerPort: 5004
              protocol: TCP
          imagePullPolicy: "{{ .Values.fineract_connector.imagePullPolicy }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 5004
            periodSeconds: 120
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5004
            failureThreshold: 90
            periodSeconds: 15
          args:
            - java
            - -XX:InitialRAMPercentage=$(JVM_INITIAL_RAM_PERCENT)
            - -XX:MaxRAMPercentage=$(JVM_MAX_RAM_PERCENT)
            - -javaagent:/app/config/elastic/elastic-apm-agent.jar
            - -jar
            - /app/ph-ee-connector-ams-fineract.jar
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.fineract_connector.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: {{ .Values.zeebe_broker_contactpoint }}
            - name: "AMS_LOCAL_ENABLED"
              value: "{{ .Values.fineract_connector.ams.local.enabled }}"
            - name: "FINERACT_BASE-URL"
              value: "{{ .Values.fineract_connector.fineract.base_url }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.fineract_connector.LOGGING_LEVEL_ROOT }}"
            - name: JVM_INITIAL_RAM_PERCENT
              value: "{{ .Values.fineract_connector.JVM_INITIAL_RAM_PERCENT }}"
            - name: JVM_MAX_RAM_PERCENT
              value: "{{ .Values.fineract_connector.JVM_MAX_RAM_PERCENT }}"
            - name: ELASTIC_APM_SERVICE_NAME
              value: "{{ .Values.fineract_connector.APM_SERVICE_NAME }}"
            - name: ELASTIC_APM_SERVER_URLS
              value: "{{ .Values.elasticsearch.APM_SERVER_URLS }}"
            - name: ELASTIC_APM_SECRET_TOKEN
              value: "{{ .Values.elasticsearch.ELASTIC_APM_SECRET_TOKEN }}"
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: "{{ .Values.fineract_connector.ELASTIC_APM_APPLICATION_PACKAGES }}"
          resources:
            limits:
              memory: "{{ .Values.fineract_connector.limits.memory }}"
              cpu: "{{ .Values.fineract_connector.limits.cpu }}"
            requests:
              memory: "{{ .Values.fineract_connector.requests.memory }}"
              cpu: "{{ .Values.fineract_connector.requests.cpu }}"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-ams-fineract
  name: ph-ee-connector-ams-fineract
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
    - name: tomcat
      port: 82
      protocol: TCP
      targetPort: 5004
  selector:
    app: ph-ee-connector-ams-fineract
  sessionAffinity: None
  type: ClusterIP

{{- end }}
