{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: ph-ee-importer-rdbms
  labels:
    app: ph-ee-importer-rdbms
spec:
  replicas: {{ .Values.importer_rdbms.replicas }}
  selector:
    matchLabels:
      app: ph-ee-importer-rdbms
  template:
    metadata:
      labels:
        app: ph-ee-importer-rdbms
      annotations:
{{- if .Values.importer_rdbms.deployment.annotations }}
{{ toYaml .Values.importer_rdbms.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-importer-rdbms
          image: "{{ .Values.importer_rdbms.image }}:{{ .Values.importer_rdbms.imageTag }}"
          imagePullPolicy: "{{ .Values.importer_rdbms.imagePullPolicy }}"
          ports:
            - containerPort: 8000
          args:
            - java
            - -XX:InitialRAMPercentage=$(JVM_INITIAL_RAM_PERCENT)
            - -XX:MaxRAMPercentage=$(JVM_MAX_RAM_PERCENT)
            - -javaagent:/config/elastic/elastic-apm-agent.jar
            - -jar
            - /app/app.jar
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.operations.SPRING_PROFILES_ACTIVE }}"
            - name: "DATASOURCE_CORE_USERNAME"
              value: "{{ .Values.importer_rdbms.datasource.username }}" 
            - name: "DATASOURCE_CORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "importer-rdbms-secret"
                  key: "database-password"
            - name: "DATASOURCE_CORE_HOST"
              value: "{{ .Values.importer_rdbms.datasource.host }}"
            - name: "DATASOURCE_CORE_PORT"
              value: "{{ .Values.importer_rdbms.datasource.port }}"
            - name: "DATASOURCE_CORE_SCHEMA"
              value: "{{ .Values.importer_rdbms.datasource.schema }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.importer_rdbms.LOGGING_LEVEL_ROOT }}"
            - name: "LOGGING_PATTERN_CONSOLE"
              value: "{{ .Values.importer_rdbms.LOGGING_PATTERN_CONSOLE }}"
            - name: JVM_INITIAL_RAM_PERCENT
              value: "{{ .Values.importer_rdbms.JVM_INITIAL_RAM_PERCENT }}"
            - name: JVM_MAX_RAM_PERCENT
              value: "{{ .Values.importer_rdbms.JVM_MAX_RAM_PERCENT }}"
            - name: ELASTIC_APM_SERVICE_NAME
              value: "{{ .Values.importer_rdbms.APM_SERVICE_NAME }}"
            - name: ELASTIC_APM_SERVER_URLS
              value: "{{ .Values.elasticsearch.APM_SERVER_URLS }}"
            - name: ELASTIC_APM_SECRET_TOKEN
              value: "{{ .Values.elasticsearch.ELASTIC_APM_SECRET_TOKEN }}"
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: "{{ .Values.importer_rdbms.ELASTIC_APM_APPLICATION_PACKAGES }}"
          resources:
            limits:
              memory: "{{ .Values.importer_rdbms.limits.memory }}"
              cpu: "{{ .Values.importer_rdbms.limits.cpu }}"
            requests:
              memory: "{{ .Values.importer_rdbms.requests.memory }}"
              cpu: "{{ .Values.importer_rdbms.requests.cpu }}"
---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: importer-rdbms-secret
type: Opaque
data:
  database-password: {{ .Values.importer_rdbms.datasource.password | b64enc }}
{{- end }}